name    'hardening/apache_hardening'
version '0.1.0'
source 'https://github.com/TelekomLabs/puppet-apache-hardening'
author 'Markus Schmall'
license 'Apache License, Version 2.0'
summary 'Configures Apache for security hardening'
description 'Configures Apache for security hardening'
project_page 'https://github.com/TelekomLabs/puppet-apache-hardening'

dependency 'hardening/hardening_stdlib', '>=0.0.0 <1.0.0'
dependency 'puppetlabs/apache'

